---
# Install Python on first boot. Can't gather_facts w/out it so remaioning tasks 
# will be performed in another playbook

- name: Install Python on initial boot
  hosts: polana2
  gather_facts: no
  tasks:

  - name: apt update
    raw: apt update

  - name: apt upgrade
    raw: apt upgrade -y

  - name: install Python3
    raw: apt install -y python3 

  - name: reboot
    ansible.builtin.reboot:
