---
# Install and provision an SD card on localhost (before first boot.)
- name: Provision SD card before initial boot
  hosts: localhost
  connection: local 
  tasks:

# Build a list of mounted partitions and unmount if found
  - name: build list of mounted partitions
    shell: "df 2>/dev/null|grep {{ssd_dev}}|awk '{print $1}'"
    register: "partitions"

  - name: list mounted partitions
    debug: var=partitions.stdout_lines

  - name: unmount partitions
    become: yes
    shell: "umount {{ item }}"
    with_items: "{{ partitions.stdout_lines }}"

# execute blkdiscard if the image name is provided
  - name: erase SSD (blkdiscard)
    become: yes
    shell: "blkdiscard -f {{ssd_dev}}"
    when: os_image is defined

# copy OS image
  - name: copy OS image
    become: yes
    shell: "xzcat {{os_image}} > {{ssd_dev}}"
    when: os_image is defined
