---
# perform tasks to configure a fairly generic Debian install
# e.g. no ZFS or Docker
# Note: A ZFS filesystem is created by the preboot playbook
# (provision-Debian.yml) and this can be reformatted as desired.
# after the environment is sufficiently configured. (e.g. Python)

- name: Bulk of setup during second boot
  hosts: all
  vars:
    config_system_locale: 'en_US.UTF-8'
    config_system_language: 'en_US.UTF-8'
  tasks:

# install some programs
  - name: update/upgrade
    apt:
      cache_valid_time: 3600
      install_recommends: no
      upgrade: yes
      autoclean: yes

  - name: install commonly used applications
    apt:
      pkg:
      - vim
      - tree
      - lsof
      - mbuffer
      - s-tui
      - stress-ng
      - rsync
      - git
      - lzop
      - iperf3
      - locales
      - tmux
      - wget
      - smartmontools
      - time
      - ethtool
      - sudo

# timezone
  - name: Set timezone 
    timezone:
      name: America/Chicago

# Locale
  - name: Ensure a locale exists
    community.general.locale_gen:
      name: en_US.UTF-8
      state: present
  
# add user "hbarta"
  - name: add user hbarta
    user:
      name: hbarta
      comment: HB
      shell: /bin/bash
      generate_ssh_key: 'yes'
      create_home: 'yes'
      groups: sudo
      append: 'yes'
      password: $6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1
      # 'mypassword'

# Force password change on first login
  - name: force password change
    command: passwd --expire hbarta

# Change ownership of home dir
  - name: fix /home/hbarta ownership
    file:
      path: /home/hbarta
      owner: hbarta
      group: hbarta
 
